"""
Quantum-Behaved Particle Swarm Optimization (QPSO) for VRP.
Milestone 4: Quantum-Inspired Swarm Optimization.

Mathematical Formulation & Quantum Mechanics Analogy:
In classical mechanics and classical PSO, particles follow deterministic Newtonian trajectories
defined by velocity vectors. In Quantum Mechanics (Schrodinger equation), particles exhibit wave-particle
duality and exist in probability density clouds within potential wells (Sun, Feng, Xu, 2004).

Key Quantum-Inspired Concepts:
1. Delta Potential Well:
   Particles move in a quantum delta potential well centered at a local attractor:
       P_{i} = phi * P_{best, i} + (1 - phi) * G_{best},  where phi ~ U(0, 1)

2. Mean Best Position (mbest):
   The collective center of the swarm's memory:
       mbest = (1 / PopSize) * sum_{i=1}^{PopSize} P_{best, i}
   In discrete permutation space, mbest is represented by the edge-frequency precedence consensus
   matrix across all swarm personal bests.

3. Wave Function & Quantum Tunneling:
   The probability density follows a double exponential distribution:
       Q(x) ~ (1 / L) * exp(-2 * |x - P| / L)
   Position updates are governed by:
       X_{i, t+1} = P_{i} +/- alpha * |mbest - X_{i, t}| * ln(1 / u),  u ~ U(0, 1)

4. Contraction-Expansion Parameter (alpha):
   Controls the convergence rate and quantum search radius. Dynamically decreases from
   alpha_start (1.0) to alpha_end (0.5) to transition from global quantum exploration to local exploitation.

5. Discrete Permutation Mapping:
   - Consensus Attractor P_i: Generated by probabilistic edge-recombination between P_best and G_best.
   - Quantum Radius L: Measures the Hamming / swap distance between X_i and the mbest consensus.
   - Quantum Tunneling Moves: Stochastic permutation inversions and route mutations whose intensity
     is scaled by alpha * L * ln(1 / u), enabling particles to tunnel out of local traps.
"""

import time
import math
import random
from typing import List, Dict, Any, Optional, Tuple

from models.vrp_models import VRPProblemDefinition, VRPMatrixInfo, VehicleRoute
from optimization.encoding import (
    DiscreteVRPSolution,
    compute_permutation_difference,
    create_initial_random_solution,
)
from optimization.objective import ObjectiveFunction, shared_objective_function


class QPSOParticle:
    """Individual quantum-behaved search particle."""

    def __init__(self, initial_solution: DiscreteVRPSolution):
        self.position: DiscreteVRPSolution = initial_solution.copy()
        self.fitness: float = float("inf")
        self.breakdown: Dict[str, Any] = {}

        self.pbest_position: DiscreteVRPSolution = initial_solution.copy()
        self.pbest_fitness: float = float("inf")


class QPSOSolver:
    """
    Quantum-Behaved Particle Swarm Optimization Solver for CVRP-TW.
    Implements quantum state dynamics, mean best consensus, and contraction-expansion search.
    """

    def __init__(
        self,
        population_size: int = 40,
        max_iterations: int = 80,
        alpha_start: float = 1.0,
        alpha_end: float = 0.5,
        objective: Optional[ObjectiveFunction] = None,
        random_seed: Optional[int] = None,
    ):
        self.population_size = max(10, population_size)
        self.max_iterations = max(10, max_iterations)
        self.alpha_start = alpha_start
        self.alpha_end = alpha_end
        self.objective = objective or shared_objective_function
        self.random_seed = random_seed
        self.rng = random.Random(random_seed) if random_seed is not None else random.Random()

    def _compute_mean_best_consensus(
        self, swarm: List[QPSOParticle], customer_ids: List[str]
    ) -> Dict[Tuple[str, str], float]:
        """
        Calculates the discrete Mean Best (mbest) edge precedence matrix across all swarm P_best solutions.
        Returns edge transition frequencies representing the collective swarm memory.
        """
        edge_counts: Dict[Tuple[str, str], int] = {}
        total = len(swarm)

        for p in swarm:
            tour, _ = p.pbest_position.to_giant_tour()
            for idx in range(len(tour) - 1):
                pair = (tour[idx], tour[idx + 1])
                edge_counts[pair] = edge_counts.get(pair, 0) + 1

        # Normalized edge probabilities
        mbest_freq: Dict[Tuple[str, str], float] = {
            k: v / total for k, v in edge_counts.items()
        }
        return mbest_freq

    def _generate_local_attractor(
        self,
        pbest: DiscreteVRPSolution,
        gbest: DiscreteVRPSolution,
        phi: float,
        num_vehicles: int,
        all_customers: List[str],
    ) -> DiscreteVRPSolution:
        """
        Constructs the quantum local attractor P_i = phi * P_best + (1 - phi) * G_best.
        Performs crossover recombination between P_best and G_best weighted by quantum probability phi.
        """
        p_tour, p_cuts = pbest.to_giant_tour()
        g_tour, g_cuts = gbest.to_giant_tour()
        n = len(p_tour)

        # Order Crossover (OX) based on quantum factor phi
        if self.rng.random() < phi:
            parent1, parent2 = p_tour, g_tour
            cuts = p_cuts
        else:
            parent1, parent2 = g_tour, p_tour
            cuts = g_cuts

        if n >= 2:
            i, j = sorted(self.rng.sample(range(n), 2))
            subset = set(parent1[i : j + 1])
            attractor_tour = [None] * n
            attractor_tour[i : j + 1] = parent1[i : j + 1]

            fill_idx = 0
            for item in parent2:
                if item not in subset:
                    while fill_idx < n and attractor_tour[fill_idx] is not None:
                        fill_idx += 1
                    if fill_idx < n:
                        attractor_tour[fill_idx] = item
                        fill_idx += 1
            attractor_tour = [item for item in attractor_tour if item is not None]
        else:
            attractor_tour = list(parent1)

        sol = DiscreteVRPSolution.from_giant_tour(attractor_tour, cuts, num_vehicles)
        return sol.repair_and_validate(all_customers)

    def solve(
        self,
        problem: VRPProblemDefinition,
        matrix_info: VRPMatrixInfo,
    ) -> Dict[str, Any]:
        """
        Executes Quantum-Behaved PSO search for near-optimal customer orderings and vehicle assignments.
        """
        start_time = time.perf_counter()

        all_customer_ids = [c.id for c in problem.customers]
        num_vehicles = len(problem.vehicles) if problem.vehicles else 2

        if not all_customer_ids:
            return {
                "algorithm": "Quantum-Inspired QPSO",
                "status": "error",
                "message": "No customers to optimize.",
            }

        # 1. Quantum Swarm Initialization
        swarm: List[QPSOParticle] = []
        gbest_position: Optional[DiscreteVRPSolution] = None
        gbest_fitness: float = float("inf")
        gbest_routes: List[VehicleRoute] = []
        gbest_breakdown: Dict[str, Any] = {}

        for _ in range(self.population_size):
            init_sol = create_initial_random_solution(all_customer_ids, num_vehicles, self.rng)
            init_sol = init_sol.repair_and_validate(all_customer_ids)
            particle = QPSOParticle(init_sol)

            fit, bdown, c_res, routes = self.objective.evaluate(
                particle.position.routes, problem, matrix_info
            )
            particle.fitness = fit
            particle.breakdown = bdown
            particle.pbest_fitness = fit
            particle.pbest_position = particle.position.copy()

            if fit < gbest_fitness:
                gbest_fitness = fit
                gbest_position = particle.position.copy()
                gbest_routes = routes
                gbest_breakdown = bdown

            swarm.append(particle)

        convergence_history: List[float] = [gbest_fitness]
        iteration_snapshots: List[Dict[str, Any]] = [
            {
                "iteration": 0,
                "fitness": gbest_fitness,
                "distance_km": gbest_breakdown.get("raw_metrics", {}).get("distance_km", 0.0),
                "travel_time_min": gbest_breakdown.get("raw_metrics", {}).get("total_duration_min", 0.0),
                "routes": [list(r) for r in gbest_position.routes] if gbest_position else [],
            }
        ]

        # 2. Main QPSO Optimization Loop
        for iteration in range(1, self.max_iterations + 1):
            # Contraction-Expansion parameter alpha decreases linearly
            alpha = self.alpha_start - (self.alpha_start - self.alpha_end) * (
                iteration / self.max_iterations
            )

            # Compute collective Mean Best (mbest) consensus
            mbest_freq = self._compute_mean_best_consensus(swarm, all_customer_ids)

            for particle in swarm:
                # A. Quantum Local Attractor P_i calculation
                phi = self.rng.random()
                attractor = self._generate_local_attractor(
                    particle.pbest_position,
                    gbest_position,
                    phi,
                    num_vehicles,
                    all_customer_ids,
                )

                # B. Quantum Divergence / Search Radius
                # Distance to mbest: count how many edges in particle differ from mbest consensus
                curr_tour, _ = particle.position.to_giant_tour()
                distance_to_mbest = 0
                for idx in range(len(curr_tour) - 1):
                    pair = (curr_tour[idx], curr_tour[idx + 1])
                    if mbest_freq.get(pair, 0.0) < 0.2:
                        distance_to_mbest += 1

                # Quantum radius step: L = alpha * |mbest - X| * ln(1/u)
                u = max(1e-5, min(0.99999, self.rng.random()))
                quantum_step = alpha * max(1.0, float(distance_to_mbest)) * math.log(1.0 / u)
                num_tunneling_moves = int(math.ceil(min(5, quantum_step)))

                # C. State Update: start from attractor and apply quantum tunneling rotations
                new_sol = attractor.copy()

                sign = 1 if self.rng.random() > 0.5 else -1
                for _ in range(num_tunneling_moves):
                    if sign > 0:
                        new_sol = new_sol.mutate_2opt(self.rng)
                    else:
                        new_sol = new_sol.mutate_swap(self.rng)

                # Stochastic vehicle partition boundary mutation
                if self.rng.random() < 0.3:
                    new_sol = new_sol.mutate_vehicle_shift(self.rng)

                # D. Ensure solution repair and customer uniqueness
                new_sol = new_sol.repair_and_validate(all_customer_ids)
                particle.position = new_sol

                # E. Objective Evaluation
                fit, bdown, c_res, routes = self.objective.evaluate(
                    particle.position.routes, problem, matrix_info
                )
                particle.fitness = fit
                particle.breakdown = bdown

                # F. Update Personal Best
                if fit < particle.pbest_fitness:
                    particle.pbest_fitness = fit
                    particle.pbest_position = particle.position.copy()

                # G. Update Global Best
                if fit < gbest_fitness:
                    gbest_fitness = fit
                    gbest_position = particle.position.copy()
                    gbest_routes = routes
                    gbest_breakdown = bdown

            convergence_history.append(gbest_fitness)
            if iteration == 1 or iteration % 10 == 0 or iteration == self.max_iterations:
                iteration_snapshots.append({
                    "iteration": iteration,
                    "fitness": gbest_fitness,
                    "distance_km": gbest_breakdown.get("raw_metrics", {}).get("distance_km", 0.0),
                    "travel_time_min": gbest_breakdown.get("raw_metrics", {}).get("total_duration_min", 0.0),
                    "routes": [list(r) for r in gbest_position.routes] if gbest_position else [],
                })

        elapsed_ms = (time.perf_counter() - start_time) * 1000.0

        return {
            "algorithm": "Quantum-Inspired QPSO",
            "status": "success",
            "is_feasible": gbest_breakdown.get("is_feasible", False),
            "best_fitness": gbest_fitness,
            "convergence_history": convergence_history,
            "iteration_snapshots": iteration_snapshots,
            "iterations_completed": self.max_iterations,
            "population_size": self.population_size,
            "execution_time_ms": round(elapsed_ms, 2),
            "fitness_breakdown": gbest_breakdown,
            "total_distance_km": gbest_breakdown.get("raw_metrics", {}).get("distance_km", 0.0),
            "total_travel_time_min": gbest_breakdown.get("raw_metrics", {}).get("total_duration_min", 0.0),
            "best_routes": gbest_position.routes if gbest_position else [],
            "decoded_routes": gbest_routes,
            "parameters": {
                "population_size": self.population_size,
                "iterations": self.max_iterations,
                "alpha_start": self.alpha_start,
                "alpha_end": self.alpha_end,
                "random_seed": self.random_seed,
            },
        }
